name: build

on:
  push:
    branches: [ "dev/pipecheck" ]
  pull_request:
    branches: [ "dev/pipecheck" ]

jobs:
  test:
    name: release
    runs-on: windows-latest
    steps:
      - name: Setup Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@release/v1
      - name: Check out source code
        uses: actions/checkout@v2
	with:
	  submodule: recursive
#      - name: Compile and run some C code
#        shell: cmd
#        run: |
#          cl.exe hello.c
#          cl.exe hello2.cpp
#          hello.exe
#          hello.exe | hello2.exe
      - name: Compile and run some C code
        shell: cmd
        run: |
          make check
          hello.exe
          hello.exe | hello2.exe
  audit:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - run: npm audit --audit-level=moderate --production
      - run: npm audit --audit-level=critical
